import NavigationBar from "@/components/Navbar";
import "./globals.css";
import { Providers } from "./providers";
import { Alata } from "@next/font/google";

const alata = Alata({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={alata.className}>
        <Providers>
          <NavigationBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
